Added DesolateWinters World Generation
Terasology/AdditionalWorlds pull request #12
Opened 2017-12-11 09:51 UTC by SufurElite

2017-12-11 18:16 UTC, Cervator requested changes
Pretty good! Needs a couple changes though, primarily a texture rename and some consideration for randomness :-)

On a side note: I guess the setup here in AdditionalWorlds is becoming problematic, as some of the different student worlds are registering the same things leading to crashes. I had to locally delete the other worlds before I could get this one to run

2017-12-11 18:16 UTC, Cervator commented on assets/blocks/blocks/ThickSnow.block
> +
Since you seem to want this block as unique from regular snow you may also want to name its image accordingly to avoid confusion / ambiguity :-) 

Edit: Actually, after testing it, it doesn't actually grab the right texture this way. I can find ThickSnow blocks but they get the "default" texture.

2017-12-11 18:16 UTC, Cervator commented on src/main/java/org/terasology/desolateWinterWorldGeneration/DesolateWinterWorldGenerator.java
> +import org.terasology.core.world.generator.facetProviders.*;
Please avoid wildcard imports like this - there is a setting in IntelliJ that sets the minimum number of classes from a package before collapsing to wildcard, if you set that really high (like 99) you should be able to avoid those automatically :-)

2017-12-11 18:16 UTC, Cervator commented on src/main/java/org/terasology/desolateWinterWorldGeneration/DesolateWinterWorldRasterizer.java
> +        Random random = new Random();
Note that for randomness in world gen it is generally important to use the world seed - that way results are deterministic. If not each world generator thread ends up working with different randomness meaning you can't predict when, say, a tree overlaps between two chunks. Or if a chunk is regenerated it may end up looking differently the second time.

In this case you may be OK if you're just using it to vary snow types. But I think you might be able to spot some quirks if you go looking.

If you use the internal `FastRandom` you can pass in a seed value :-)

2019-04-21 16:17 UTC, skaldarnar commented
When trying to start a new world the game crashes with the following error:

```
java.lang.RuntimeException: Cannot set a changed component with a null component variable
	at org.terasology.persistence.internal.EntityDelta.setChangedComponent(EntityDelta.java:34)
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentChange(EntitySetDeltaRecorder.java:70)
	at org.terasology.persistence.internal.EntitySetDeltaRecorder.onEntityComponentAdded(EntitySetDeltaRecorder.java:61)
	at org.terasology.persistence.internal.ReadWriteStorageManager.onEntityComponentAdded(ReadWriteStorageManager.java:528)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.notifyComponentAdded(PojoEntityManager.java:704)
	at org.terasology.entitySystem.entity.internal.PojoEntityManager.addComponent(PojoEntityManager.java:539)
	at org.terasology.entitySystem.entity.internal.BaseEntityRef.addComponent(BaseEntityRef.java:167)
	at org.terasology.engine.modes.loadProcesses.CreateWorldEntity.step(CreateWorldEntity.java:101)
	at org.terasology.engine.modes.StateLoading.update(StateLoading.java:255)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
	at org.terasology.engine.Terasology.main(Terasology.java:156)
```

Merging anyways to clean up the PRs and repo - hopefully we can fix this later.

2019-04-21 16:21 UTC, merged