Lava Land terrain generation improvements
Terasology/AdditionalWorlds pull request #3
Opened 2017-12-01 09:57 UTC by PAndaContron

These are the changes I have made since the original one:

- New custom blocks ash and volcanic rock replace the Core blocks in the previous one

- Naturally generating petrified trees

- Naturally generating house structure made from petrified logs and volcanic rock

- Deadbushes from Core naturally generate

2017-12-01 14:14 UTC, mjuvekar7 commented
Hey I can't see any house structures. Also the bad import statement is back

2017-12-01 14:15 UTC, mjuvekar7 requested changes

2017-12-01 14:15 UTC, mjuvekar7 commented on src/main/java/org/terasology/lavalandgenerator/WorldGenerator.java
> +import build.classes.org.terasology.core.world.generator.facetProviders.SeaLevelProvider;
Change this

2017-12-01 14:16 UTC, mjuvekar7 commented
Also please update your fork. We've added a screenshot directory where screenshots should be stored. Also that will prevent future merge issues

2017-12-01 19:37 UTC, PAndaContron commented
I've made the necessary changes to the code, but it turns out one of the screenshots was actually from an older version, so I'll have to wait until I have access to the computer where the screenshots are stored locally before I can replace that.

2017-12-02 06:41 UTC, mjuvekar7 commented
Looks good! When you get time, you might want to add torches inside the houses. Gets a bit hard to see inside. Might also want to look into using [StructureTemplates](https://github.com/Terasology/StructureTemplates)

2017-12-02 06:42 UTC, merged

2017-12-02 06:45 UTC, mjuvekar7 commented
Also you should update your fork before working on changes. That should prevent ugly commit trees like the above :)